/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BusinessIdRouteImport } from './routes/$businessId'
import { Route as IndexRouteImport } from './routes/index'

const BusinessIdRoute = BusinessIdRouteImport.update({
  id: '/$businessId',
  path: '/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$businessId': typeof BusinessIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$businessId': typeof BusinessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$businessId': typeof BusinessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$businessId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$businessId'
  id: '__root__' | '/' | '/$businessId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessIdRoute: typeof BusinessIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$businessId': {
      id: '/$businessId'
      path: '/$businessId'
      fullPath: '/$businessId'
      preLoaderRoute: typeof BusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessIdRoute: BusinessIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
