# Generated by Django 5.2.14 on 2026-05-25 11:38

import api.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='BusinessListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Official trading name of the business (max 100 characters)', max_length=100)),
                ('service_detail', models.TextField(help_text='Comprehensive description of services, operational specialties, and offerings (max 2000 characters)', max_length=2000)),
                ('phone_no', models.CharField(help_text='Primary contact number for customer inquiries (E.164 format, e.g., +1234567890)', max_length=20, validators=[api.validators.validate_e164_phone])),
                ('email', models.EmailField(help_text='Public contact email address for business correspondence', max_length=254)),
                ('location_link', models.URLField(help_text='Valid URL mapping link (Google Maps, Apple Maps, or OpenStreetMap coordinate URL) representing physical storefront or service area hub', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this listing is active and visible')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Whether business has been verified by admin')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this listing has been viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Business owner who manages this listing', limit_choices_to={'user_type__in': ['business_owner', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='business_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Listing',
                'verbose_name_plural': 'Business Listings',
                'db_table': 'business_listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('was_successful', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'otp_attempt_logs',
                'indexes': [models.Index(fields=['email', 'attempted_at'], name='otp_attempt_email_cb229f_idx'), models.Index(fields=['ip_address', 'attempted_at'], name='otp_attempt_ip_addr_0e7c33_idx')],
            },
        ),
        migrations.CreateModel(
            name='OTPRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'otp_request_logs',
                'indexes': [models.Index(fields=['email', 'requested_at'], name='otp_request_email_e14bdd_idx'), models.Index(fields=['ip_address', 'requested_at'], name='otp_request_ip_addr_d392d6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='businesslisting',
            index=models.Index(fields=['title'], name='business_li_title_4e56f4_idx'),
        ),
        migrations.AddIndex(
            model_name='businesslisting',
            index=models.Index(fields=['owner', 'is_active'], name='business_li_owner_i_a2312c_idx'),
        ),
        migrations.AddIndex(
            model_name='businesslisting',
            index=models.Index(fields=['is_active', 'is_verified'], name='business_li_is_acti_648815_idx'),
        ),
        migrations.AddIndex(
            model_name='businesslisting',
            index=models.Index(fields=['created_at'], name='business_li_created_79e6a7_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'is_used'], name='otps_user_id_2092b6_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expires_at'], name='otps_expires_f6308f_idx'),
        ),
    ]
