# Generated by Django 5.2.14 on 2026-05-25 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslisting',
            name='owner',
            field=models.ForeignKey(help_text='Business owner who manages this listing', on_delete=django.db.models.deletion.CASCADE, related_name='business_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
