# Generated by Django 5.0.7 on 2026-05-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_businesslisting_owner'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='businesslisting',
            name='business_li_owner_i_a2312c_idx',
        ),
        migrations.RemoveIndex(
            model_name='businesslisting',
            name='business_li_is_acti_648815_idx',
        ),
        migrations.RemoveField(
            model_name='businesslisting',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='businesslisting',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='businesslisting',
            name='location_link',
        ),
        migrations.RemoveField(
            model_name='businesslisting',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='businesslisting',
            name='view_count',
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='address',
            field=models.TextField(blank=True, help_text='Structured address (geocoded)'),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='business_category',
            field=models.CharField(blank=True, db_index=True, help_text='Category of the business (e.g., Restaurant, Plumbing, Cleaning)', max_length=50),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='businesslisting',
            index=models.Index(fields=['business_category'], name='business_li_busines_60fce2_idx'),
        ),
        migrations.AddIndex(
            model_name='businesslisting',
            index=models.Index(fields=['latitude', 'longitude'], name='business_li_latitud_ab5758_idx'),
        ),
    ]
